parameters:
- name: deployJobName
  default: ''
- name: artefactName
  default: ''
- name: azureSubscription
  default: ''
- name: webAppName
  default: ''

jobs:
  - job: ${{ parameters.deployJobName }}
    steps:
     - task: DownloadPipelineArtifact@2
       displayName: "download pipeline artifact"
       inputs:
         artifactName: ${{ parameters.artefactName }}
         targetPath: $(Build.ArtifactStagingDirectory)

     - task: AzureRmWebAppDeployment@4
       displayName: 'azure api service deployment'
       inputs:
         ConnectionType: 'AzureRM'
         azureSubscription: ${{ parameters.azureSubscription }}
         appType: 'apiApp'
         WebAppName: ${{ parameters.webAppName }}
         packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'