parameters:
- name: deployStageName
  default: ''
- name: testStageName
  default: ''
- name: jobName
  default: ''
- name: azureSubscription
  default: ''
- name: webAppName
  default: ''
- name: artefactName
  default: ''

stages:
     - stage: ${{ parameters.deployStageName }}
       dependsOn:
         - Build
       condition: succeeded('Build')
       jobs:
           - template: deployjob.yml
             parameters:
               stageName: ${{ parameters.deployStageName }}
               jobName: 'Deploy'
               azureSubscription: ${{ parameters.azureSubscription }}
               webAppName: ${{ parameters.webAppName }}
               artefactName: ${{ parameters.artefactName }}

     - stage: ${{ parameters.testStageName }}
       dependsOn:
         - DeployApp
       condition: succeeded('DeployApp')
       jobs:
           - template: testjob.yml
             parameters:
               stageName: ${{ parameters.testStageName }}
               jobName: 'Test'
               artefactName: ${{ parameters.artefactName }}   