parameters:
- name: testJobName
  default: ''
- name: artefactName
  default: ''


jobs:
  - job: ${{ parameters.testJobName }}
    steps:
     - task: DownloadPipelineArtifact@2
       displayName: "download pipeline artifact"
       inputs:
         artifactName: ${{ parameters.artefactName }}
         targetPath: $(Build.ArtifactStagingDirectory)

     - task: DotNetCoreCLI@2
       displayName: 'dotnet integration | enduser test'
       inputs:
         command: 'test'
         projects: '**/*IntTests/*.csproj'